### ISSUE TITLE
Types declaration export issue

### ISSUE THREAD

**Issue by danielmiksavmlyr** [samhirtarif/react-audio-visualize#24]
Hello,

I want to report an issue with package configuration in types declaration regards. I get an error:

```
There are types at './node_modules/react-audio-visualize/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-audio-visualize' library may need to update its package.json or typings.
```

Which means that there is a conflict between `types` and `exports` fields in `package.json`. In order to make it working properly in my project I had to add:

```
"react-audio-visualize": [
  "node_modules/react-audio-visualize/dist/index.d.ts"
]
```

in `tsconfig` under `compilerOptions.paths` key so typescript is able to resolve declaration modules properly. Possible solution might be to add `"types"` under `exports` in package.json, like this:

```
"exports": {
  ".": {
    // ... 
    "types": "./dist/index.d.ts"
  }
}
```

But would be good to double check if it really solves the problem.

Regards,

Daniel Miksa.

**Comment by samhirtarif** [comment]
#20 fixes this issue.
Fix available in v1.2.0
